### PR TITLE
Fix errors in get request exercise

### PR DESCRIPTION
**Pull request by tannerwelsh**
Looks like these were overlooked the first time around.

### CODE REVIEW

**Comment by tannerwelsh** [comment]
Hey @zspencer I think these were legitimate errors but not sure if they were intentionally a part of the "learning experience" or not.

**Comment by zspencer** [comment]
No such thing as an error left in for the learning experience :-p. Those should all have giant flashing signs in front of them saying "YOU WILL GET AN EXCEPTION. PLEASE READ IT!"

**Comment by zspencer** [comment]
:+1: for fixing these btw. My bad.

**Comment by tannerwelsh** [comment]
Yeah that was my reaction too.

Merging!

**Pull request merged**
